FROM postgres:15-alpine

# Set default environment variables
ENV POSTGRES_DB=bodaboda
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password

# Add a label for identification
LABEL maintainer="codewithmac"
LABEL description="BodaConnect PostgreSQL Database"
LABEL version="1.0"

# Expose the default postgres port
EXPOSE 5432
